/*
IMPORTAMOS TODO LO QUE TIENE COMPONENTS PARA USARLO EN OTROS COMPONENTS
ES COMO UN INDICE DE UN LIBRO AQUI DECLARAMOS TODO LO QUE TENEMOS EN
EL COMPONENTE
*/

export * from "./Button/Button.tsx"
export * from "./ButtonPersonalizado/ButtonPS.tsx"